### ISSUE TITLE
hex、unicode编码

### ISSUE THREAD

**Issue by xiaoyanyuha** [smxiazi/xia_sql#1]
可以考虑引号加个hex、unicode编码绕过，如果大佬比较忙，麻烦发下源码，我可以代劳，会写点java代码

**Comment by smxiazi** [comment]
只是添加单引号和-1、-0，很少有waf会去拦截吧。

**Comment by smxiazi** [comment]
代码开源出来了，能帮我添加个右键可以发送到这个插件里面的功能么，我感觉这么写，要实现这个功能，得重构。
