### ISSUE TITLE
json中的插入点不对

### ISSUE THREAD

**Issue by alpha302** [smxiazi/xia_sql#29]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/55012418/177456787-fd8e8330-4402-42b2-9cb2-a76a58e893ce.png">

**Comment by smxiazi** [comment]
这种是参数嵌套json的，暂时当成字符串处理，后期会修复这个问题。

**Comment by daomeixiong1048** [comment]
![图片](https://user-images.githubusercontent.com/101961135/181199941-80236750-214d-472a-a50d-e8dfe4ac1c62.png)
json中插入就成了这样
