### ISSUE TITLE
存在的注入的单独加一个显示框

### ISSUE THREAD

**Issue by test502git** [smxiazi/xia_sql#3]
看起来有点太多了，把可能存在的注入的，再单独加一个显示框，比较明了

**Comment by smxiazi** [comment]
xia SQL 2.3
新增 状态一列，run…… 表示正在发送相关payload，end! 表示已经扫描完成，end! ✔️表示扫描完成且结果可能存在注入。

这样可以满足该需求。

**Comment by kingz40o** [comment]
为何不把不存在注入的不显示出来呢

**Comment by smxiazi** [comment]
如果不显示出来。还以为插件出问题 ，这样可感知状态就没有了
