### ISSUE TITLE
![图片](https://user-images.githubusercontent.com/101961135/181199941-80236750-214d-472a-a50d-e8dfe4ac1c62.png)

### ISSUE THREAD

**Issue by smxiazi** [smxiazi/xia_sql#31]
![图片](https://user-images.githubusercontent.com/101961135/181199941-80236750-214d-472a-a50d-e8dfe4ac1c62.png)
json中插入就成了这样

_Originally posted by @daomeixiong1048 in https://github.com/smxiazi/xia_sql/issues/29#issuecomment-1196421512_

**Comment by smxiazi** [comment]
@daomeixiong1048  原始数据包发我一下

**Comment by daomeixiong1048** [comment]
@smxiazi 
`POST / HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
Accept: */*
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=UTF-8
Content-Length: 77
Connection: close
Cookie: PHPSESSID=10628e0b660c7474fbb00d2e3d3a5e22

{"stat":"1","wxgmc":"1","cjwdno":"99999999","wxgno":"xxx","page":1,"size":10}`

**Comment by smxiazi** [comment]
已修复，请更新
