### ISSUE TITLE
二进制流下的参数识别问题（binary/octet-stream）

### ISSUE THREAD

**Issue by Amaake3321** [smxiazi/xia_sql#37]
如下图所示，会识别到很多莫名其妙的参数导致跑100+包
类型为binary/octet-stream

![image](https://user-images.githubusercontent.com/50546208/216491178-cec4f922-bc86-4918-842e-ceb394fd93ed.png)

**Comment by smxiazi** [comment]
收到，之前也发现这个问题，一直懒着去优化，准备去修复这个bug。

**Comment by smxiazi** [comment]
更新了，这个问题修复了
