### ISSUE TITLE
[feature-request] 能不能走burp被动扫描而不是监控proxy

### ISSUE THREAD

**Issue by peter5he1by** [smxiazi/xia_sql#50]
一般插件被动扫描是由burp主动把请求发给插件来扫（利用burpsuite的被动扫描功能，这个过程可以由scope控制，这样很多被动扫描插件不需要单独配置黑白名单），而瞎注用的是http handler，虽然拦截面广，但是还要为它单独配置白名单。所以可不可以让瞎注只走被动扫描呢？

**Comment by JaveleyQAQ** [comment]
这样我建议你直接新建一个实时扫描任务，监听proxy流量，把audit检查项自定义为sql，但是每个包至少会发送300+请求😀

**Comment by JaveleyQAQ** [comment]
![image](https://github.com/smxiazi/xia_sql/assets/132129852/ed6b8996-aabf-4af0-a660-cc115bb030f8)
![image](https://github.com/smxiazi/xia_sql/assets/132129852/109271fe-90f0-4bb5-a0b3-5af3e9249462)

**Comment by peter5he1by** [comment]
好的谢谢
